# Generated by Django 5.0 on 2026-02-06 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escrowdispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Escrow Dispute', 'verbose_name_plural': 'Escrow Disputes'},
        ),
        migrations.AlterModelOptions(
            name='escrowstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Escrow Status History', 'verbose_name_plural': 'Escrow Status Histories'},
        ),
        migrations.AlterModelOptions(
            name='escrowtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Escrow Transaction', 'verbose_name_plural': 'Escrow Transactions'},
        ),
        migrations.RenameField(
            model_name='escrowstatushistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='resolution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refund/release', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='seller_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='escrowdispute',
            name='buyer_evidence',
            field=models.TextField(blank=True, help_text="Buyer's evidence"),
        ),
        migrations.AlterField(
            model_name='escrowdispute',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='escrow.escrowtransaction'),
        ),
        migrations.AlterField(
            model_name='escrowdispute',
            name='reason',
            field=models.CharField(choices=[('not_received', 'Item Not Received'), ('wrong_item', 'Wrong Item Delivered'), ('damaged', 'Item Damaged'), ('not_as_described', 'Not as Described'), ('counterfeit', 'Counterfeit/Fake Product'), ('defective', 'Defective Product'), ('other', 'Other Reason')], max_length=50),
        ),
        migrations.AlterField(
            model_name='escrowdispute',
            name='seller_evidence',
            field=models.TextField(blank=True, help_text="Seller's evidence"),
        ),
        migrations.AlterField(
            model_name='escrowdispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_buyer', 'Resolved - Buyer Favor'), ('resolved_seller', 'Resolved - Seller Favor'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowstatushistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Order amount', max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, help_text='Auto-release date (14 days after delivery)', null=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='auto_release_days',
            field=models.IntegerField(default=14, help_text='Days until auto-release after delivery'),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='2.5% escrow fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='payment_provider',
            field=models.CharField(blank=True, default='flutterwave', max_length=50),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Flutterwave transaction ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('in_escrow', 'In Escrow'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount + escrow fee', max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['transaction_id'], name='escrow_escr_transac_35b41f_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['buyer', '-created_at'], name='escrow_escr_buyer_i_3d6ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['seller', '-created_at'], name='escrow_escr_seller__061a54_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['status'], name='escrow_escr_status_9ea6b9_idx'),
        ),
    ]
