"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import cloudinary
import cloudinary.uploader
import cloudinary.api
import os
from decouple import config
from pathlib import Path
from django.utils.translation import gettext_lazy as _



import sys
import django

if sys.version_info >= (3, 14) and django.VERSION < (5, 1):
    print(f"⚠️  Detected Python {sys.version_info.major}.{sys.version_info.minor} with Django {django.get_version()}")
    print("   Applying compatibility patches...")
    
    # Patch 1: Fix BaseContext.__copy__
    try:
        from django.template import context
        
        class PatchedBaseContext(context.BaseContext):
            def __copy__(self):
                """Fixed copy for Python 3.14"""
                duplicate = self.__class__()
                # Directly access dicts instead of using super()
                if hasattr(self, 'dicts'):
                    for d in self.dicts:
                        duplicate.update(d)
                return duplicate
        
        # Replace the class
        context.BaseContext = PatchedBaseContext
        print("   ✓ Patched BaseContext.__copy__")
    except Exception as e:
        print(f"   ✗ Failed to patch BaseContext: {e}")
    
    # Patch 2: Fix Context class
    try:
        from django.template.context import Context
        
        original_context_copy = Context.__copy__
        
        def patched_context_copy(self):
            try:
                return original_context_copy(self)
            except (AttributeError, TypeError):
                # Manual copy
                duplicate = Context()
                for d in self.dicts:
                    duplicate.update(d)
                return duplicate
        
        Context.__copy__ = patched_context_copy
        print("   ✓ Patched Context.__copy__")
    except Exception as e:
        print(f"   ✗ Failed to patch Context: {e}")
    
    # Patch 3: Fix RequestContext
    try:
        from django.template.context import RequestContext
        
        original_request_context_copy = RequestContext.__copy__
        
        def patched_request_context_copy(self):
            try:
                return original_request_context_copy(self)
            except (AttributeError, TypeError):
                # Manual copy with request
                duplicate = RequestContext(self.request)
                for d in self.dicts:
                    duplicate.update(d)
                return duplicate
        
        RequestContext.__copy__ = patched_request_context_copy
        print("   ✓ Patched RequestContext.__copy__")
    except Exception as e:
        print(f"   ✗ Failed to patch RequestContext: {e}")
    
    print("   ✓ All patches applied successfully")
    print("   This is a temporary fix. Please upgrade to Django 5.1+ or use Python 3.12/3.13")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4hf-7p#$xy*l+(#dx^9*%t3(t=p)3cd8yqto3e9s52$4c&v*!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['afrimart-production.up.railway.app']
if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]

CLOUDINARY_URL = config('CLOUDINARY_URL', default='')

CSRF_TRUSTED_ORIGINS = [
    "https://afrimart-production.up.railway.app",
]

if CLOUDINARY_URL:
    cloudinary.config()
else:
    # Fallback configuration
    cloudinary.config(
        cloud_name='dplyxhcu1',
        api_key=config('CLOUDINARY_API_KEY', default=''),
        api_secret=config('CLOUDINARY_API_SECRET', default=''),
        secure=True
    )


LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
    ('sw', _('Swahili')),
    ('ha', _('Hausa')),
    ('yo', _('Yorùbá')),
    ('ig', _('Igbo')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGES_BIDI = ['ar']


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'yomijonathan8@gmail.com'
EMAIL_HOST_PASSWORD = 'ltkukhjytfruuoxx'
DEFAULT_FROM_EMAIL = 'Afrimart <yomijonathan8@gmail.com>'
SERVER_EMAIL = 'yomijonathan8@gmail.com'

# Email addresses for different purposes
NOREPLY_EMAIL = 'yomijonathan8@gmail.com'
ORDERS_EMAIL = 'yomijonathan8@gmail.com'
SUPPORT_EMAIL = 'yomijonathan8@gmail.com'
ESCROW_EMAIL = 'yomijonathan8@gmail.com'
ADMIN_EMAIL = 'yomijonathan8@gmail.com'

# Timeout settings (important for shared hosting)
EMAIL_TIMEOUT = 30


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'main',
    'escrow',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # moved here per Django docs
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processor.cart_processor',
                'main.context_processor.currency_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


SITE_URL = 'http://127.0.0.1:8000'  

# Auth redirects
# Use the named 'login' view so LocaleMiddleware (i18n_patterns) can resolve the language-prefixed login URL
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

USE_BUCKET = os.getenv("USE_BUCKET", "false") == "true"

if USE_BUCKET:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
    AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
    AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
    AWS_S3_ENDPOINT_URL = os.environ["AWS_S3_ENDPOINT_URL"]
    AWS_S3_REGION_NAME = "auto"
    AWS_QUERYSTRING_AUTH = False

    MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = "/data/media/"

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

# Project-level static files directory
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'escrow_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/escrow_release.log',
            'formatter': 'verbose',
        },
        'stock_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/stock_unlock.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'escrow': {
            'handlers': ['escrow_file'],
            'level': 'INFO',
        },
        'main': {
            'handlers': ['stock_file'],
            'level': 'INFO',
        },
    },
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}



