"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import cloudinary
import cloudinary.uploader
import cloudinary.api
import os
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4hf-7p#$xy*l+(#dx^9*%t3(t=p)3cd8yqto3e9s52$4c&v*!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CLOUDINARY_URL = config('CLOUDINARY_URL', default='')

if CLOUDINARY_URL:
    cloudinary.config()
else:
    # Fallback configuration
    cloudinary.config(
        cloud_name='dplyxhcu1',
        api_key=config('CLOUDINARY_API_KEY', default=''),
        api_secret=config('CLOUDINARY_API_SECRET', default=''),
        secure=True
    )



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Your hosting's SMTP server (check cPanel)
EMAIL_HOST = 'mail.techfy.africa' 
EMAIL_PORT = 465

EMAIL_USE_SSL = True
# Your email credentials
EMAIL_HOST_USER = 'noreply@techfy.africa'
EMAIL_HOST_PASSWORD = 'RO*(_3+%]FT]GK$_'

# From email
DEFAULT_FROM_EMAIL = 'Afrimart <noreply@techfy.africa>'
SERVER_EMAIL = 'admin@techfy.africa'

# Email addresses for different purposes
NOREPLY_EMAIL = 'noreply@techfy.africa'
ORDERS_EMAIL = 'orders@techfy.africa'
SUPPORT_EMAIL = 'support@techfy.africa'
ESCROW_EMAIL = 'escrow@techfy.africa'
ADMIN_EMAIL = 'admin@techfy.africa'

# Timeout settings (important for shared hosting)
EMAIL_TIMEOUT = 30


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'main',
    'escrow',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processor.cart_processor',
                'main.context_processor.currency_processor' 
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


SITE_URL = 'http://127.0.0.1:8000'  

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

# Project-level static files directory
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'escrow_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/escrow_release.log',
            'formatter': 'verbose',
        },
        'stock_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/stock_unlock.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'escrow': {
            'handlers': ['escrow_file'],
            'level': 'INFO',
        },
        'main': {
            'handlers': ['stock_file'],
            'level': 'INFO',
        },
    },
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}



