# Generated by Django 5.0 on 2026-02-01 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_wallet_amount_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
