# Generated by Django 5.0 on 2026-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'order'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='main_produc_is_prim_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='User is a seller/vendor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_approved',
            field=models.BooleanField(default=False, help_text='Seller account is approved'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_description',
            field=models.TextField(blank=True, help_text='Seller business description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_store_name',
            field=models.CharField(blank=True, help_text='Store name for sellers', max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
